package learn.java.program;


public class Try_Catch_Program
{

	
	/*public static void main(String[] args)
	{*/	
		/*ArithmeticException*/
		/*try 
		{ 
			System.out.print("Hello" + " " + 1 / 0); 
		} 
		catch(ArithmeticException e) 
		{ 
			System.out.print("Payilagam"); 
		} */

		/*try 
		{
			int a, b; b = 0; a = 5 / b; 
			System.out.print("Hi"); 
		} 
		catch(ArithmeticException e) 
		{
			System.out.print("Hello"); 
		}
		finally 
		{ 
			System.out.print("Vanakkam"); 
		} */
		/*try 
		{ 
			int i, sum; sum = 10;
			for (i = -1; i < 3 ;++i) 
			{
				sum = (sum / i); 
				System.out.println(i); 
			}
		}
			catch(ArithmeticException e) 
			{ 
				System.out.print("Payilagam"); 
			} */
		/*public static void aMethod() throws Exception 
		{ 
			try  Line 5  
			{ 
				throw new Exception();  Line 7  
				
			} finally  Line 9  
			{
				System.out.println("finally ");  Line 11 
			}
		} 
		public static void main(String args[]) 
		{ 
			try 
			{ 
				aMethod(); 
			} catch (Exception e)  Line 20  
			{
				System.out.println("exception "); 
			} System.out.println("finished");  Line 24  
			
		}*/
		/*try 
		{ 
			throw new Ast(); 
		} catch(Ast t) 
		{
			System.out.println("Payilagam "); 
		} finally 
		{ 
			System.out.println("Chennai finally"); 
		} */
	 /* String str = "a"; 
	  void A() 
	  { 
		  try 
		  { 
			  str +="b"; B(); 
			 } 
		  catch (Exception e) 
			 { 
				 str += "c";
			} 
		  } 
	  void B() throws Exception 
		  {
			  try {
				  str += "d"; 
				  C(); 
				  }
			  catch(Exception e) 
				  { 
					  throw new Exception(); 
				  } 
			  finally 
				  { 
					  str += "e"; 
				  } 
			  str += "f"; 
				  }
		  void C() throws Exception 
				  { 
					  throw new Exception(); 
				 } 
		  void display() 
				 {
					 System.out.println(str); 
					 }
				 public static void main(String[] args)
				 {
					 Ast object = new Ast();
					 object.A();
					 object.display();
				 }*/
//}
		 
		
		} 

		
	


	

//}
